# render.yaml
services:
  - type: web
    name: ai-visionpro-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: MAPS_API_KEY
        sync: false
    build:
      pythonVersion: 3.10.11
